# These are supported funding model platforms

github: sajib1066
patreon: sajib1066
open_collective: sajib1066
ko_fi: sajib1066
tidelift: pypi/makeportfolios
community_bridge: Makeportfolios
liberapay: sajib1066
issuehunt: sajib1066
otechie: sajib1066
custom: https://sajib1066.github.io/
